### ISSUE TITLE
should Wrapf(nil, ...) return nil?

### ISSUE THREAD

**Issue by cben** [zgalor/weberr#8]
The behavior when the wrapped error is nil — `weberr.Wrapf(nil, "foo %d", 42)` — is undocumented.  
Currently it returns a new "foo 42" error:
https://github.com/zgalor/weberr/blob/54d909cf8ea646df84bfdce1491596ea034dffda/errors.go#L182-L186
The upstream `errors.Wrapf(nil, "foo %d", 42)` returns nil:
https://github.com/pkg/errors/blob/49f8f617296114c890ae0b7ac18c5953d2b1ca0f/errors.go#L200-L204

I propose to align with upstream, which is widely used and understood, even if it breaks compatibility with previous weberr.
Some cons/pros below, none very strong, so IMHO keeping this a drop-in replacement to pkg/errors is the decisive point.
@zgalor @vkareh @etabak @nshneor what do you think?

### against

upstream nil behavior was **opposed** in https://github.com/pkg/errors/issues/174, and while it's closed — they clearly won't break compatiblity for this — I can empatize with some use cases there.  They're are solvable by conditionally calling `errors.New()` vs `.Wrapf()` but that's annoying.

EDIT: there was more discussion on https://github.com/pkg/errors/issues/90, where Dave did say "if I was doing this again today I would not have put in this convenience" but that he won't break compatibility.

### pro

In our non-public codebase, I'm not sure we ever called Wrapf outside an `if err != nil {` block.  But now I have minor a use case where I'd like to:

We have some helpers for conditional error handling, one of which I now tried to rewrite to:
```
==> helpers.go <==
func Check(ctx context.Context, err error, msg string) {
	if err != nil {
		// with some magic I'm adding, 
		// this will dump err message AND weberr.GetStackTrace(err)!
		log.Ctx(ctx).WithError(err).Fatal(msg)
	}
}

==> some_business_logic.go <==
	helpers.Check(ctx, err, "Service terminated with errors")
```
An annoyance is that for both logrus file:line detection, and for weberr stack traces, you always see `helper.go:100` instead of the specific place that called `Check(...)` :confounded: 
A trick that I learnt from logrus is to keep the call that captures file:line info in the bussiness logic :bulb:.  So I thought to rewrite to this:
```
==> some_business_logic.go <==
// Wrapf called here captures `some_business_logic.go:200` into stack trace!
	helpers.Check(ctx, weberr.Wrapf("Service terminated with errors: %s", err))

// in helpers.go
func Check(ctx context.Context, err error) {
	if err != nil {
		log.Ctx(ctx).WithError(err).Fatal("")
	}
}
```
However, if `Wrapf()` turns nil into a new error without cause, that won't work as Check() will always receive _some_ error and won't know whether it should exit...

(There are other ways to allow helper functions to work, I know)

**Comment by cben** [comment]
Update: seeing more opposition on https://github.com/pkg/errors/issues/90, where the author at one point regrets (but can't change) the nil=>nil behavior, I retract my use case.

Calling `Wrapf()` with explicit desire that it preserves `nil` is very unobvious to the reader.
If I'll want to do that, I'll want a function with more expressive name e.g. `WrapIfError(...)`...

weberr should pick something, and **document**.

**Comment by zgalor** [comment]
@tzvatot and I had a use case in our code base, and our discussion resulted in this behavior where `Wrapf(nil, "something")` will create a new error.
So, this is the behavior chosen. 
@tzvatot, do you recall the use case?

**Comment by tzvatot** [comment]
@zgalor we had several bugs where the developer wrote "Wrapf(err, ...)" and the result was nil due to err==nil.
Although you may argue that the user misused the library, wrapping a nil value - still the result of "Wrapf" is not expected to return nil. And the price to pay for such errors is very high.
So we decided to return an error, even if the internal err is nil.

**Comment by vkareh** [comment]
> An annoyance is that for both logrus file:line detection, and for weberr stack traces, you always see helper.go:100 instead of the specific place that called Check(...) confounded

Discussed offline, but adding for completion: We can use `filenameHook.SkipPrefixes` from [onrik/logrus](https://github.com/onrik/logrus) to avoid this issue.

```go
filenameHook := filename.NewHook()
filenameHook.Field = "file"
filenameHook.SkipPrefixes = append(filenameHook.SkipPrefixes, "cmd/foo/bar/handler_helpers.go")
logrus.AddHook(filenameHook)
```

**Comment by cben** [comment]
Okay :+1: I'll send a doc PR

**Comment by cben** [comment]
documented in #9.
